apiVersion: v1
kind: Pod
metadata:
  name: volume-ephemeral
  labels:
    hello: world
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
      - mountPath: /scratch
        name: scratch-volume
  - name: busybox
    image: busybox
    command: ["/bin/sh", "-c"]
    args: ["sleep 10000"]
    volumeMounts:
      - mountPath: /scratch
        name: scratch-volume
  volumes:
    - name: scratch-volume
      emptyDir:
        sizeLimit: 500Mi
