apiVersion: v1
kind: Pod
metadata:
  name: debug
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: /app/data
      name: mealie-data
  volumes:
    - name: mealie-data
      persistentVolumeClaim:
        claimName: mealie-data
